[package]

name = "grpc"
version = "0.0.2"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "README.md"
keywords = ["grpc"]

[dependencies]
log             = "0.3"
#solicit         = { git = "http://github.com/mlalic/solicit.git" }
solicit-fork   = { git = "http://github.com/stepancheg/solicit.git" }
hpack          = "0.3"
#protobuf       = { path = "../rust-protobuf" }
protobuf        = { git = "http://github.com/stepancheg/rust-protobuf" }
#futures         = { git = "https://github.com/alexcrichton/futures-rs" }
futures         = "0.*"
#futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs" }
futures-cpupool = "0.*"
tokio-core      = "0.*"
tokio-tls       = { git = "https://github.com/tokio-rs/tokio-tls/"}

openssl = { version = "0.8", optional = true }

[lib]
doctest = false

[workspace]
members = [
    "grpc-examples",
    "grpc-compiler",
    "long-tests/with-rust",
]

